---
settings:
  name: Astra Control Center
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: release-notes/whats-new.html
  versions:
  - version-number: '24.02'
    url: "/astra-control-center"
  - version-number: '23.10'
    url: "/astra-control-center-2310"
  - version-number: '23.07'
    url: "/astra-control-center-2307"
  - version-number: '23.04'
    url: "/astra-control-center-2304"
  - version-number: '22.11'
    url: "/astra-control-center-2211"
  - version-number: '22.08'
    url: "/astra-control-center-2208"
  - version-number: '22.04'
    url: "/astra-control-center-2204"
  - version-number: '21.12'
    url: "/astra-control-center-2112"
  - version-number: '21.08'
    url: "/astra-control-center-2108"
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Astra Control Center - Dokumentation
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: concepts
  - section: use
  - section: use-acp
  - section: rest-api
  - section: support
  - title: Frühere Versionen
    url: "/acc-earlier-versions.html"
  - title: Häufig gestellte Fragen
    url: "/get-started/faq.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
