---
settings:
  name: Astra Control Center
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: release-notes/whats-new.html
  versions:
  - name: Astra Control Center
    url: "/astra-control-center"
    version-number: '22.11'
  - name: Astra Control Center
    url: "/astra-control-center-2208"
    version-number: '22.08'
  - name: Astra Control Center
    url: "/astra-control-center-2204"
    version-number: '22.04'
  - name: Astra Control Center
    url: "/astra-control-center-2112"
    version-number: '21.12'
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: Astra Control Center - Dokumentation
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: concepts
  - section: use
  - section: rest-api
  - section: support
  - title: Frühere Versionen
    url: "/acc-earlier-versions.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Starten Sie jetzt mit Astra Control Center
    links:
    - title: Erfahren Sie mehr über Astra Control Center
      url: "/get-started/intro.html"
    - title: Was ist neu im Astra Control Center
      url: "/release-notes/whats-new.html"
    - title: Versionshinweise
      url: "/release-notes/rn_overview.html"
    - title: Probieren Sie es aus
      url: "/get-started/quick-start.html"
    - title: Installieren Sie Astra Control Center
      url: "/get-started/install_acc.html"
  - title: Nutzen Sie Das Astra Control Center
    links:
    - title: Konten verwalten
      url: "/use/manage-local-users-and-roles.html"
    - title: Applikationsmanagement
      url: "/use/manage-apps.html"
    - title: Schützen von Applikationen
      url: "/use/protect-apps.html"
    - title: Klonen und Migrieren von Applikationen
      url: "/use/clone-apps.html"
    - title: Replizieren von Apps auf einem Remote-System
      url: "/use/replicate_snapmirror.html"
  - title: Verwenden Sie die Astra Control REST-API
    links:
    - title: Erste Schritte mit der Astra Control API
      url: https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html
    - title: API-Referenz
      url: https://docs.netapp.com/us-en/astra-automation/reference/overview.html
    - title: API-Workflows
      url: https://docs.netapp.com/us-en/astra-automation/workflows/workflows_before.html
  - title: Nutzen Sie Den Astra Control Service
    links:
    - title: Erfahren Sie mehr über den Astra Control Service
      url: https://docs.netapp.com/us-en/astra/get-started/intro.html
    - title: Was ist neu im Astra Control Service
      url: https://docs.netapp.com/us-en/astra/release-notes/whats-new.html
    - title: Schnellstart für den Astra Control Service
      url: https://docs.netapp.com/us-en/astra/get-started/quick-start.html
  - title: Lösungen im Überblick
    links:
    - title: PostgreSQL DBaaS mit Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
    - title: MySQL DBaaS mit Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
    - title: Vereinfachung des Lifecycle Managements von Jenkins
      url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
  - title: Blogs Community
    links:
    - title: Kanal abstecken
      url: https://discord.gg/NetApp
    - title: Astra Control Blog
      url: https://cloud.netapp.com/blog/topic/astra
    - title: NetApp Community
      url: https://community.netapp.com/
    - title: Kubernetes Hub
      url: https://cloud.netapp.com/kubernetes-hub
    - title: Wo Sie Hilfe erhalten
      url: "/support/get-help.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Die komplette Astra Dokumentation
