= Laden Sie das Astra Control Center herunter und extrahieren Sie es
:allow-uri-read: 




== Laden Sie das Astra Control Center herunter und extrahieren Sie es

Laden Sie die Bilder des Astra Control Center von einem der folgenden Standorte herunter:

* *Astra Control Service Image Registry*: Verwenden Sie diese Option, wenn Sie keine lokale Registrierung mit den Astra Control Center Images verwenden oder wenn Sie diese Methode dem Bundle-Download von der NetApp Support-Website vorziehen.
* *NetApp Support-Seite*: Verwenden Sie diese Option, wenn Sie eine lokale Registrierung mit den Astra Control Center-Images verwenden.


[role="tabbed-block"]
====
.Astra Control-Image-Registrierung
--
. Melden Sie sich beim Astra Control Service an.
. Wählen Sie im Dashboard *Deploy a self-Managed Instance of Astra Control* aus.
. Folgen Sie den Anweisungen, um sich bei der Astra Control-Image-Registrierung anzumelden, das Astra Control Center-Installationsabbild zu ziehen und das Image zu extrahieren.


--
.NetApp Support Website
--
. Laden Sie das Bundle mit Astra Control Center herunter (`astra-control-center-[version].tar.gz`) Vom https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Download-Seite für Astra Control Center"^].
. (Empfohlen, aber optional) Laden Sie das Zertifikaten- und Unterschriftenpaket für Astra Control Center herunter (`astra-control-center-certs-[version].tar.gz`) Um die Signatur des Bündels zu überprüfen.
+
[source, console]
----
tar -vxzf astra-control-center-certs-[version].tar.gz
----
+
[source, console]
----
openssl dgst -sha256 -verify certs/AstraControlCenter-public.pub -signature certs/astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----
+
Die Ausgabe wird angezeigt `Verified OK` Nach erfolgreicher Überprüfung.

. Extrahieren Sie die Bilder aus dem Astra Control Center Bundle:
+
[source, console]
----
tar -vxzf astra-control-center-[version].tar.gz
----


--
====