---
sidebar: sidebar 
permalink: concepts/licensing.html 
keywords: license, licensing 
summary: Erfahren Sie, wie sich die Aktionen mit dem Astra Control Center je nach Lizenzstatus unterscheiden und wie sich Ihre Verwendung von Astra Control Center auf den Lizenzverbrauch auswirkt. 
---
= Lizenzierung
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Astra Control Center erfordert die Installation einer Lizenz, damit die vollständige App-Datenmanagement-Funktion aktiviert werden kann. Wenn Sie Astra Control Center ohne Lizenz bereitstellen, wird in der Web-UI ein Banner angezeigt, in dem Sie darauf hingewiesen werden, dass die Systemfunktionalität begrenzt ist.

Sie erhalten eine Lizenz auf eine der folgenden Arten:

* link:https://mysupport.netapp.com/site/downloads/evaluation/astra-control-center["Wenn Sie Astra Control Center evaluieren, laden Sie die Evaluierungslizenzdatei herunter"^]. Mit einer Evaluierungslizenz können Sie das Astra Control Center 90 Tage ab dem Datum, an dem Sie die Lizenz herunterladen, verwenden.
* link:https://mysupport.netapp.com/site/["Wenn Sie Astra Control Center bereits gekauft haben, generieren Sie Ihre NetApp Lizenzdatei (NLF)."^] Von der NetApp Support Site aus. Nach dem Kauf des Produkts erhalten Sie eine Seriennummer und eine Lizenz, die Sie auf der Support-Website verwenden.


Details zu Lizenzen, die für ONTAP Storage Back-Ends erforderlich sind, finden Sie unter link:../get-started/requirements.html["Unterstützte Storage-Back-Ends"].


NOTE: Sie können ohne Lizenz ein Cluster hinzufügen, einen Bucket hinzufügen und ein Storage-Backend verwalten.



== Berechnung der Lizenznutzung

Wenn Sie dem Astra Control Center einen neuen Cluster hinzufügen, zählen diese nicht auf verbrauchte Lizenzen, bis mindestens eine auf dem Cluster ausgeführte Applikation vom Astra Control Center verwaltet wird.

Wenn Sie eine App auf einem Cluster managen, sind alle CPU-Einheiten des Clusters im Lizenzverbrauch des Astra Control Center enthalten.



== Weitere Informationen

* link:../get-started/setup_overview.html#add-a-license-for-astra-control-center["Fügen Sie beim ersten Einrichten des Astra Control Center eine Lizenz hinzu"]
* link:../use/update-licenses.html["Aktualisieren einer vorhandenen Lizenz"]

