---
sidebar: sidebar 
permalink: concepts/licensing.html 
keywords: license, licensing 
summary: Erfahren Sie, wie sich die Aktionen mit dem Astra Control Center je nach Lizenzstatus unterscheiden und wie sich Ihre Verwendung von Astra Control Center auf den Lizenzverbrauch auswirkt. 
---
= Lizenzierung
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Astra Control Center erfordert die Installation einer Lizenz, damit die vollständige App-Datenmanagement-Funktion aktiviert werden kann. Wenn Sie Astra Control Center ohne Lizenz bereitstellen, wird in der Web-UI ein Banner angezeigt, in dem Sie darauf hingewiesen werden, dass die Systemfunktionalität begrenzt ist.

Sie benötigen eine Lizenz zum Schutz Ihrer Applikationen und Daten. Siehe Astra Control Center link:../concepts/intro.html["Funktionen"] Entsprechende Details.

Nach dem Kauf des Produkts erhalten Sie eine Seriennummer und eine Lizenz. Sie können die NetApp Lizenzdatei (NetApp License File, NLF) von generieren https://mysupport.netapp.com["NetApp Support Website"^].

Sie können das Astra Control Center auch mit einer Evaluierungslizenz ausprobieren, mit der Sie das Astra Control Center 90 Tage ab dem Tag, an dem Sie die Lizenz herunterladen, nutzen können. Weitere Informationen finden Sie unter link:../get-started/requirements.html["Anforderungen"].

Details zu Lizenzen, die für ONTAP Storage Back-Ends erforderlich sind, finden Sie unter link:../get-started/requirements.html["Unterstützte Storage-Back-Ends"].


NOTE: Sie können ohne Lizenz ein Cluster hinzufügen, einen Bucket hinzufügen und ein Storage-Backend verwalten.



== Berechnung der Lizenznutzung

Wenn Sie dem Astra Control Center einen neuen Cluster hinzufügen, zählen diese nicht auf verbrauchte Lizenzen, bis mindestens eine auf dem Cluster ausgeführte Applikation vom Astra Control Center verwaltet wird.

Wenn Sie eine App auf einem Cluster verwalten, sind alle CPU-Einheiten dieses Clusters im Lizenzverbrauch des Astra Control Center enthalten.



== Weitere Informationen

* link:../use/update-licenses.html["Aktualisieren einer vorhandenen Lizenz"]

