---
sidebar: sidebar 
permalink: use/manage-backend.html 
keywords: how to use astra control, what is astra storage, how to set up astra storage backend, ontap storage in astra, backend storage in astra 
summary: 'Durch das Management von Storage-Clustern in Astra Control als Storage-Backend können Sie Verbindungen zwischen persistenten Volumes (PVS) und dem Storage-Backend sowie zusätzliche Storage-Kennzahlen abrufen. Sie können Details zur Storage-Kapazität und zum Zustand überwachen.' 
---
= Management des Storage-Backends
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Durch das Management von Storage-Clustern in Astra Control als Storage-Backend können Sie Verbindungen zwischen persistenten Volumes (PVS) und dem Storage-Backend sowie zusätzliche Storage-Kennzahlen abrufen.

Eine Anleitung zum Managen von Storage-Back-Ends mithilfe der Astra Control API finden Sie im link:https://docs.netapp.com/us-en/astra-automation/["Astra Automation und API-Informationen"^].

Sie können die folgenden Aufgaben zur Verwaltung eines Storage-Backends ausführen:

* link:../get-started/add-storage-backend.html["Fügen Sie ein Storage-Back-End hinzu"]
* <<Details zum Storage-Back-End>>
* <<Bearbeiten Sie die Details der Storage-Back-End-Authentifizierung>>
* <<Management eines erkannten Storage-Backends>>
* <<Unmanagement eines Storage-Backends>>
* <<Entfernen Sie ein Speicher-Back-End>>




== Details zum Storage-Back-End

Sie können Speicher-Backend-Informationen über das Dashboard oder über die Option Back-Ends anzeigen.



=== Details zum Storage-Back-End können Sie über das Dashboard anzeigen

.Schritte
. Wählen Sie in der linken Navigationsleiste *Dashboard* aus.
. Überprüfen Sie den Back-End-Bereich Speicher des Dashboards, der den Status anzeigt:
+
** *Ungesund*: Die Lagerung befindet sich nicht im optimalen Zustand. Dies kann durch ein Latenzproblem oder eine Applikation aufgrund eines Container-Problems, z. B., beeinträchtigt sein.
** *Alles gesund*: Die Lagerung wurde verwaltet und ist in einem optimalen Zustand.
** *Entdeckt*: Der Speicher wurde entdeckt, aber nicht von Astra Control verwaltet.






=== Details zum Speicher-Backend über die Option „Backend“ anzeigen

Informationen zum Zustand, Kapazität und Performance des Backend (IOPS-Durchsatz und/oder Latenz)

Sie sehen die Volumes, die die Kubernetes-Apps verwenden, die in einem ausgewählten Storage-Backend gespeichert sind.

.Schritte
. Wählen Sie im linken Navigationsbereich *Backend* aus.
. Wählen Sie das Storage-Back-End aus.




== Bearbeiten Sie die Details der Storage-Back-End-Authentifizierung

Astra Control Center bietet zwei Arten der Authentifizierung eines ONTAP-Backends.

* *Credential-basierte Authentifizierung*: Der Benutzername und das Passwort an einen ONTAP-Benutzer mit den erforderlichen Berechtigungen. Sie sollten eine vordefinierte Sicherheits-Login-Rolle wie admin verwenden, um maximale Kompatibilität mit ONTAP-Versionen zu gewährleisten.
* *Zertifikatbasierte Authentifizierung*: Astra Control Center kann auch mit einem ONTAP-Cluster kommunizieren, indem ein auf dem Backend installiertes Zertifikat verwendet wird. Verwenden Sie gegebenenfalls das Clientzertifikat, den Schlüssel und das Zertifikat der vertrauenswürdigen Zertifizierungsstelle (empfohlen).


Sie können vorhandene Back-Ends aktualisieren, um von einem Authentifizierungstyp zu einer anderen zu wechseln. Es wird jeweils nur eine Authentifizierungsmethode unterstützt.

Weitere Informationen zum Aktivieren der zertifikatbasierten Authentifizierung finden Sie unter link:../get-started/enable-auth-ontap-backend.html["Aktivieren Sie die Authentifizierung auf dem ONTAP Storage Back-End"].

.Schritte
. Wählen Sie in der linken Navigationsleiste *Backend* aus.
. Wählen Sie das Storage-Back-End aus.
. Wählen Sie im Feld Anmeldeinformationen das Symbol *Bearbeiten* aus.
. Wählen Sie auf der Seite Bearbeiten eine der folgenden Optionen aus.
+
** *Administrator-Anmeldeinformationen verwenden*: Geben Sie die ONTAP Cluster Management IP-Adresse und die Admin-Anmeldeinformationen ein. Die Anmeldedaten müssen Cluster-weite Anmeldedaten aufweisen.
+

NOTE: Der Benutzer, dessen Anmeldeinformationen Sie hier eingeben, muss über den verfügen `ontapi` Aktivieren der Zugriffsmethode für die Anmeldung beim Benutzer in ONTAP System Manager auf dem ONTAP Cluster. Wenn Sie Vorhaben, SnapMirror Replizierung zu verwenden, wenden Sie Benutzeranmeldeinformationen auf die Rolle „Admin“ an, die über die Zugriffsmethoden verfügt `ontapi` Und `http`, Auf Quell- und Ziel-ONTAP Clustern. Siehe https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_cluster_user_accounts.html#users-list["Managen von Benutzerkonten in der ONTAP Dokumentation"^] Finden Sie weitere Informationen.

** *Ein Zertifikat* verwenden: Das Zertifikat hochladen `.pem` Datei, dem Zertifikatschlüssel `.key` Datei und optional die Zertifizierungsdatei.


. Wählen Sie *Speichern*.




== Management eines erkannten Storage-Backends

Sie können auswählen, wie ein nicht verwaltetes, aber dennoch ermitteltes Storage-Back-End verwaltet werden soll. Wenn Sie ein Storage-Backend verwalten, gibt Astra Control an, ob ein Authentifizierungszertifikat abgelaufen ist.

.Schritte
. Wählen Sie in der linken Navigationsleiste *Backend* aus.
. Wählen Sie die Option *entdeckt*.
. Wählen Sie das Storage-Back-End aus.
. Wählen Sie im Menü Optionen in der Spalte *Aktionen* *Verwalten* aus.
. Nehmen Sie die Änderungen vor.
. Wählen Sie *Speichern*.




== Unmanagement eines Storage-Backends

Sie können das Backend verwalten.

.Schritte
. Wählen Sie in der linken Navigationsleiste *Backend* aus.
. Wählen Sie das Storage-Back-End aus.
. Wählen Sie im Menü Optionen in der Spalte *Aktionen* die Option *Verwaltung aufheben* aus.
. Geben Sie „unverwalten“ ein, um die Aktion zu bestätigen.
. Wählen Sie *Ja, verwalten Sie das Speicher-Backend*.




== Entfernen Sie ein Speicher-Back-End

Sie können ein nicht mehr verwendenden Storage-Back-End entfernen. Nutzen Sie dies, um Ihre Konfiguration auf dem neuesten Stand zu halten.

.Bevor Sie beginnen
* Stellen Sie sicher, dass das Storage-Back-End nicht gemanagt wird.
* Stellen Sie sicher, dass dem Cluster keine Volumes im Speicher-Backend zugewiesen sind.


.Schritte
. Wählen Sie in der linken Navigationsleiste *Backend* aus.
. Wenn das Backend verwaltet wird, managen Sie es rückgängig.
+
.. Wählen Sie *Verwaltet*.
.. Wählen Sie das Storage-Back-End aus.
.. Wählen Sie aus der Option *Aktionen* die Option *Verwaltung aufheben* aus.
.. Geben Sie „unverwalten“ ein, um die Aktion zu bestätigen.
.. Wählen Sie *Ja, verwalten Sie das Speicher-Backend*.


. Wählen Sie *Entdeckt*.
+
.. Wählen Sie das Storage-Back-End aus.
.. Wählen Sie aus der Option *Aktionen* die Option *Entfernen*.
.. Geben Sie „Entfernen“ ein, um die Aktion zu bestätigen.
.. Wählen Sie *Ja, Speicher-Backend entfernen*.






== Weitere Informationen

* https://docs.netapp.com/us-en/astra-automation["Verwenden Sie die Astra Control API"^]

