---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: Fügen Sie Ihrem Konto Anmeldedaten für Cloud-Provider jederzeit hinzu und entfernen Sie sie. Astra nutzt diese Anmeldedaten für die Bereitstellung von Ressourcen in Ihrem Namen. 
---
= Anmeldeinformationen hinzufügen und entfernen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Fügen Sie Anmeldedaten für lokale Private-Cloud-Provider wie ONTAP S3, mit OpenShift gemanagte Kubernetes-Cluster oder nicht gemanagte Kubernetes-Cluster jederzeit in Ihrem Konto hinzu und entfernen Sie sie. Astra Control Center verwendet diese Zugangsdaten, um Kubernetes-Cluster und die Applikationen auf den Clustern zu erkennen und Ressourcen in Ihrem Auftrag bereitzustellen.

Beachten Sie, dass alle Benutzer im Astra Control Center dieselben Anmeldedaten verwenden.



== Anmeldedaten hinzufügen

Wenn Sie Cluster verwalten, können Sie Astra Control Center Anmeldeinformationen hinzufügen. Informationen zum Hinzufügen von Anmeldeinformationen durch Hinzufügen eines neuen Clusters finden Sie unter link:../get-started/setup_overview.html#add-cluster["Fügen Sie einen Kubernetes-Cluster hinzu"].


IMPORTANT: Wenn Sie Ihre eigenen erstellen `kubeconfig` Datei, Sie sollten nur ein *ein*-Kontext-Element darin definieren. Siehe https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Kubernetes-Dokumentation"^] Weitere Informationen zum Erstellen `kubeconfig` Dateien:



== Anmeldedaten entfernen

Entfernen Sie die Anmeldeinformationen jederzeit aus einem Konto. Sie sollten erst nach dem Entfernen von Anmeldeinformationen verwenden link:unmanage.html["Verwalten aller zugehörigen Cluster wird aufgehoben"].


NOTE: Der erste Satz von Anmeldeinformationen, die Sie dem Astra Control Center hinzufügen, wird immer verwendet, da Astra Control Center die Zugangsdaten für die Authentifizierung beim Backup-Bucket verwendet. Diese Anmeldedaten sollten am besten nicht entfernt werden.

.Schritte
. Wählen Sie *Konto*.
. Wählen Sie die Registerkarte *Anmeldeinformationen* aus.
. Wählen Sie in der Spalte *Status* das Menü Optionen für die Anmeldeinformationen aus, die Sie entfernen möchten.
. Wählen Sie *Entfernen*.
. Geben Sie das Wort „Entfernen“ ein, um den Löschvorgang zu bestätigen, und wählen Sie dann *Ja, Anmeldedaten entfernen* aus.


Astra Control Center entfernt die Anmeldeinformationen aus dem Konto.
