---
sidebar: sidebar 
permalink: use/manage-remote-users-groups.html 
keywords: import, import users, search, search users, groups, import groups 
summary: Verwalten Sie Remote-LDAP-Benutzer und -Gruppen auf Ihrem Astra Control Center-System. 
---
= Verwalten von Remote-Benutzern und -Gruppen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Wenn Sie die LDAP-Authentifizierung auf Ihrem Astra Control System aktiviert haben, können Sie nach LDAP-Benutzern und -Gruppen suchen und diese in die genehmigten Benutzer des Systems aufnehmen.



== Fügen Sie einen Remote-Benutzer hinzu

Kontoinhaber und -Administratoren können Remote-Benutzer zu Astra Control hinzufügen. Astra Control Center unterstützt bis zu 10,000 LDAP Remote-Benutzer.


IMPORTANT: Astra Control Center verwendet das bei aktivierter Remote-Authentifizierung konfigurierte Attribut für die Benutzeranmeldung, um Remote-Benutzer zu suchen und zu verfolgen. Für jeden Remote-Benutzer, den Sie im Astra Control Center anzeigen möchten, muss in diesem Feld ein Attribut einer E-Mail-Adresse („Mail“) oder eines Hauptnamens des Benutzers („userPrincipalName“) vorhanden sein. Dieses Attribut wird als Benutzername in Astra Control Center für die Authentifizierung und bei der Suche nach Remote-Benutzern verwendet.


NOTE: Sie können keinen Remote-Benutzer hinzufügen, wenn bereits ein lokaler Benutzer mit derselben E-Mail-Adresse (basierend auf dem Attribut „Mail“ oder „user principal Name“) auf dem System vorhanden ist. Um den Benutzer als Remote-Benutzer hinzuzufügen, löschen Sie zuerst den lokalen Benutzer aus dem System.

.Schritte
. Gehen Sie zum Bereich *Konto*.
. Wählen Sie die Registerkarte *Benutzer & Gruppen* aus.
. Wählen Sie rechts auf der Seite die Option *Remote Users*.
. Wählen Sie *Hinzufügen*.
. Sie können auch nach einem LDAP-Benutzer suchen, indem Sie die E-Mail-Adresse des Benutzers im Feld *Filtern nach E-Mail* eingeben.
. Wählen Sie einen oder mehrere Benutzer aus der Liste aus.
. Weisen Sie dem Benutzer eine Rolle zu.
+

NOTE: Wenn Sie einem Benutzer und der Gruppe des Benutzers verschiedene Rollen zuweisen, hat die Rolle eine größere Priorität.

. Weisen Sie diesem Benutzer optional eine oder mehrere Namespace-Einschränkungen zu und wählen Sie *Rolle auf Einschränkungen beschränken* aus, um sie durchzusetzen. Sie können eine neue Namespace-Einschränkung hinzufügen, indem Sie *Bedingung hinzufügen* auswählen.
+

NOTE: Wenn einem Benutzer mehrere Rollen durch die LDAP-Gruppenmitgliedschaft zugewiesen werden, sind die Einschränkungen in der am stärksten permissivsten Rolle die einzigen, die wirksam werden. Wenn z. B. ein Benutzer mit einer lokalen Viewer-Rolle drei Gruppen verbindet, die an die Rolle Mitglied gebunden sind, wird die Summe der Einschränkungen aus den Mitgliederrollen wirksam, und alle Einschränkungen aus der Viewer-Rolle werden ignoriert.

. Wählen Sie *Hinzufügen*.


.Ergebnis
Der neue Benutzer wird in der Liste der Remote-Benutzer angezeigt. In dieser Liste können Sie aktive Einschränkungen für den Benutzer sehen und den Benutzer über das Menü *Aktionen* verwalten.



== Fügen Sie eine externe Gruppe hinzu

Wenn Sie viele Remote-Benutzer gleichzeitig hinzufügen möchten, können Kontoinhaber und -Administratoren Remote-Gruppen zu Astra Control hinzufügen. Wenn Sie eine Remote-Gruppe hinzufügen, können sich alle Remote-Benutzer in dieser Gruppe bei Astra Control anmelden und übernehmen die gleiche Rolle wie die Gruppe.

Astra Control Center unterstützt bis zu 5,000 LDAP-Remote-Gruppen.

.Schritte
. Gehen Sie zum Bereich *Konto*.
. Wählen Sie die Registerkarte *Benutzer & Gruppen* aus.
. Wählen Sie rechts auf der Seite *Remote-Gruppen* aus.
. Wählen Sie *Hinzufügen*.
+
In diesem Fenster sehen Sie eine Liste der gemeinsamen Namen und Distinguished Names der LDAP-Gruppen, die Astra Control aus dem Verzeichnis abgerufen hat.

. Suchen Sie optional nach einer LDAP-Gruppe, indem Sie den gemeinsamen Namen der Gruppe in das Feld *Filter nach gemeinsamem Namen* eingeben.
. Wählen Sie eine oder mehrere Gruppen aus der Liste aus.
. Weisen Sie den Gruppen eine Rolle zu.
+

NOTE: Die ausgewählte Rolle ist allen Benutzern in dieser Gruppe zugewiesen. Wenn Sie einem Benutzer und der Gruppe des Benutzers verschiedene Rollen zuweisen, hat die Rolle eine größere Priorität.

. Weisen Sie dieser Gruppe optional eine oder mehrere Namespace-Einschränkungen zu und wählen Sie *Rolle auf Einschränkungen beschränken* aus, um sie durchzusetzen. Sie können eine neue Namespace-Einschränkung hinzufügen, indem Sie *Bedingung hinzufügen* auswählen.
+

NOTE: Wenn einem Benutzer mehrere Rollen durch die LDAP-Gruppenmitgliedschaft zugewiesen werden, sind die Einschränkungen in der am stärksten permissivsten Rolle die einzigen, die wirksam werden. Wenn z. B. ein Benutzer mit einer lokalen Viewer-Rolle drei Gruppen verbindet, die an die Rolle Mitglied gebunden sind, wird die Summe der Einschränkungen aus den Mitgliederrollen wirksam, und alle Einschränkungen aus der Viewer-Rolle werden ignoriert.

. Wählen Sie *Hinzufügen*.


.Ergebnis
Die neue Gruppe wird in der Liste der Remote-Gruppen angezeigt. Remote-Benutzer in dieser Gruppe werden erst dann in der Liste der Remote-Benutzer angezeigt, wenn sich jeder Remote-Benutzer anmeldet. In dieser Liste können Sie Details über die Gruppe anzeigen und die Gruppe über das Menü *Aktionen* verwalten.
