---
sidebar: sidebar 
permalink: use/manage-packages-acc.html 
keywords: manage package, packages, install 
summary: Sie können Pakete auf Astra Control Center hochladen und installieren. 
---
= Managen von Softwarepaketen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


NetApp bietet zusätzliche Funktionen für Astra Control Center mit Software-Paketen, die Sie von der NetApp Support-Website herunterladen können. Nachdem Sie Docker- und Artefakt-Repositorys verbunden haben, können Sie Pakete hochladen und importieren, um diese Funktion dem Astra Control Center hinzuzufügen. Sie können Softwarepakete über die CLI oder die Weboberfläche des Astra Control Center verwalten.

.Was Sie und#8217;ll benötigen
* Kubernetes-Cluster mit installiertem Astra Control Center
* Ein verbundenes Docker-Image-Repository zur Speicherung von Software-Paket-Images. Weitere Informationen finden Sie unter link:manage-connections.html["Repository-Verbindungen verwalten"].
* Ein verbundenes Artefakt-Repository zur Speicherung von Binärdateien und Artefakten für Softwarepakete Weitere Informationen finden Sie unter link:manage-connections.html["Repository-Verbindungen verwalten"].
* Ein Software-Paket von der NetApp Support Site




== Laden Sie Software-Paketbilder in die Repositorys hoch

Astra Control Center verweist auf Paketbilder und -Artefakte in angeschlossenen Repositorys. Sie können Bilder und Artefakte mithilfe der CLI in die Repositorys hochladen.

.Schritte
. Laden Sie das Software-Paket von der NetApp Support-Website herunter und speichern Sie es auf einem System, auf dem es installiert ist `kubectl` Dienstprogramm installiert.
. Extrahieren Sie die komprimierte Paketdatei und wechseln Sie das Verzeichnis zum Speicherort der Astra Control Bundle-Datei (z. B. `acc.manifest.yaml`).
. Übertragen Sie die Paket-Images auf das Docker Repository. Nehmen Sie folgende Ersetzungen vor:
+
** ERSETZEN SIE DIE BUNDLE_FILE durch den Namen der Astra Control Bundle-Datei (z. B. `acc.manifest.yaml`).
** ERSETZEN SIE MY_REGISTRY durch die URL des Docker Repositorys.
** ERSETZEN SIE MY_REGISTRY_USER durch den Benutzernamen.
** ERSETZEN SIE MY_REGISTRY_TOKEN durch ein autorisiertes Token für die Registrierung.
+
[listing]
----
kubectl astra packages push-images -m BUNDLE_FILE -r MY_REGISTRY -u MY_REGISTRY_USER -p MY_REGISTRY_TOKEN
----


. Wenn das Paket Artefakte enthält, kopieren Sie die Artefakte in das Artefakt-Repository. ERSETZEN SIE BUNDLE_FILE durch den Namen der Astra Control Bundle-Datei und NETWORK_LOCATION durch den Netzwerkspeicherort, um die Artefaktdateien zu kopieren:
+
[listing]
----
kubectl astra packages copy-artifacts -m BUNDLE_FILE -n NETWORK_LOCATION
----




== Fügen Sie ein Softwarepaket hinzu

Sie können Softwarepakete mit einer Astra Control Center-Paketdatei importieren. Dadurch wird das Paket installiert und die Software für Astra Control Center zur Verfügung gestellt.



=== Fügen Sie mithilfe der Web-Benutzeroberfläche von Astra Control ein Softwarepaket hinzu

Über die Web-Benutzeroberfläche von Astra Control Center können Sie ein Softwarepaket hinzufügen, das in die angeschlossenen Repositories hochgeladen wurde.

.Schritte
. Wählen Sie im Navigationsbereich * Konto verwalten* die Option *Konto*.
. Wählen Sie die Registerkarte *Pakete* aus.
. Klicken Sie auf die Schaltfläche *Hinzufügen*.
. Wählen Sie im Dialogfeld Dateiauswahl das Symbol Hochladen aus.
. Wählen Sie in eine Astra Control Bundle-Datei `.yaml` Format für Upload.
. Wählen Sie *Hinzufügen*.


Wenn die Bundle-Datei gültig ist und sich die Paketbilder und Artefakte in den angeschlossenen Repositorys befinden, wird das Paket dem Astra Control Center hinzugefügt. Wenn der Status in der Spalte *Status* in *verfügbar* wechselt, können Sie das Paket verwenden. Sie können den Mauszeiger auf den Status eines Pakets bewegen, um weitere Informationen zu erhalten.


NOTE: Wenn ein oder mehrere Bilder oder Artefakte für ein Paket nicht im Repository gefunden werden, wird eine Fehlermeldung für dieses Paket angezeigt.



=== Fügen Sie mithilfe der CLI ein Softwarepaket hinzu

Sie können über die CLI ein Softwarepaket importieren, das Sie in die angeschlossenen Repositories hochgeladen haben. Dazu müssen Sie zunächst Ihre Astra Control Center-Konto-ID und ein API-Token aufzeichnen.

.Schritte
. Melden Sie sich über einen Webbrowser bei der Web-UI von Astra Control Center an.
. Wählen Sie im Dashboard das Benutzersymbol rechts oben aus.
. Wählen Sie *API-Zugriff*.
. Notieren Sie sich die Konto-ID im oberen Bereich des Bildschirms.
. Wählen Sie *API-Token generieren* aus.
. Wählen Sie im daraufhin angezeigten Dialogfeld *API-Token generieren* aus.
. Notieren Sie das resultierende Token, und wählen Sie *Schließen*. Ändern Sie in der CLI die Verzeichnisse in den Speicherort des `.yaml` Paketdatei im extrahierten Paketinhalt.
. Importieren Sie das Paket mithilfe der Bundle-Datei, indem Sie folgende Ersetzungen vornehmen:
+
** ERSETZEN SIE DIE BUNDLE_FILE durch den Namen der Astra Control Bundle-Datei.
** ERSETZEN SIE DEN SERVER durch den DNS-Namen der Astra Control-Instanz.
** ERSETZEN SIE ACCOUNT_ID und TOKEN durch die Konto-ID und das API-Token, das Sie zuvor aufgezeichnet haben.
+
[listing]
----
kubectl astra packages import -m BUNDLE_FILE -u SERVER -a ACCOUNT_ID -k TOKEN
----




Wenn die Bundle-Datei gültig ist und sich die Paketbilder und Artefakte in den angeschlossenen Repositorys befinden, wird das Paket dem Astra Control Center hinzugefügt.


NOTE: Wenn ein oder mehrere Bilder oder Artefakte für ein Paket nicht im Repository gefunden werden, wird eine Fehlermeldung für dieses Paket angezeigt.



== Entfernen eines Softwarepakets

Sie können die Web-Benutzeroberfläche von Astra Control Center verwenden, um ein Softwarepaket zu entfernen, das Sie zuvor in Astra Control Center importiert haben.

.Schritte
. Wählen Sie im Navigationsbereich * Konto verwalten* die Option *Konto*.
. Wählen Sie die Registerkarte *Pakete* aus.
+
Auf dieser Seite sehen Sie die Liste der installierten Pakete und deren Status.

. Öffnen Sie in der Spalte *Aktionen* des Pakets das Menü Aktionen.
. Wählen Sie *Löschen*.


Das Paket wird aus dem Astra Control Center gelöscht, aber die Bilder und Artefakte für das Paket verbleiben in Ihren Repositorys.

[discrete]
== Weitere Informationen

* link:manage-connections.html["Repository-Verbindungen verwalten"]

