---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: Fügen Sie Benutzer zu Ihrem Astra Control Center-System hinzu und entfernen Sie Benutzer, die keinen Zugriff mehr auf das System haben sollten. 
---
= Benutzer managen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Sie können Benutzer Ihrer Astra Control Center-Installation über die Astra Control-Benutzeroberfläche einladen, hinzufügen, entfernen und bearbeiten. Sie können die Astra Control UI oder verwenden https://docs.netapp.com/us-en/astra-automation/index.html["Die Astra Control API"^] Um Benutzer zu managen.

Sie können LDAP auch zur Authentifizierung für ausgewählte Benutzer verwenden.



== LDAP verwenden

LDAP ist ein branchenübliches Protokoll für den Zugriff auf verteilte Verzeichnisinformationen und eine beliebte Wahl für die Unternehmensauthentifizierung. Sie können Astra Control Center mit einem LDAP-Server verbinden, um die Authentifizierung für ausgewählte Astra-Benutzer durchzuführen. Auf hohem Niveau beinhaltet die Konfiguration die Integration von Astra mit LDAP und die Definition der Astra-Benutzer und -Gruppen entsprechend der LDAP-Definitionen. Siehe https://docs.netapp.com/us-en/astra-automation/workflows_infra/ldap_prepare.html["LDAP-Authentifizierung"^] Finden Sie weitere Informationen.



== Benutzer einladen

Kontoinhaber und -Administratoren können neue Benutzer zum Astra Control Center einladen.

.Schritte
. Wählen Sie im Navigationsbereich * Konto verwalten* die Option *Konto*.
. Wählen Sie die Registerkarte *Benutzer* aus.
. Wählen Sie *Benutzer Einladen*.
. Geben Sie den Namen und die E-Mail-Adresse des Benutzers ein.
. Wählen Sie eine Benutzerrolle mit den entsprechenden Systemberechtigungen aus.
+
Jede Rolle bietet die folgenden Berechtigungen:

+
** Ein *Viewer* kann Ressourcen anzeigen.
** Ein *Mitglied* verfügt über Berechtigungen für Viewer-Rollen und kann Apps und Cluster verwalten, Apps verwalten und Snapshots und Backups löschen.
** Ein *Admin* verfügt über Berechtigungen für die Mitgliederrolle und kann alle anderen Benutzer außer dem Eigentümer hinzufügen und entfernen.
** Ein *Owner* hat Administratorrechte und kann beliebige Benutzerkonten hinzufügen und entfernen.


. Um einem Benutzer mit einer Mitglied- oder Viewer-Rolle Einschränkungen hinzuzufügen, aktivieren Sie das Kontrollkästchen * Rolle auf Einschränkungen beschränken*.
+
Weitere Informationen zum Hinzufügen von Einschränkungen finden Sie unter link:manage-roles.html["Rollen managen"].

. Wählen Sie *Benutzer einladen*.
+
Der Benutzer erhält eine E-Mail, in der er darüber informiert wird, dass er zum Astra Control Center eingeladen wurde. Die E-Mail enthält ein temporäres Passwort, das sie bei der ersten Anmeldung ändern müssen.





== Benutzer hinzufügen

Kontoinhaber und -Administratoren können weitere Benutzer zur Installation des Astra Control Center hinzufügen.

.Schritte
. Wählen Sie im Navigationsbereich * Konto verwalten* die Option *Konto*.
. Wählen Sie die Registerkarte *Benutzer* aus.
. Wählen Sie *Benutzer Hinzufügen*.
. Geben Sie den Namen des Benutzers, die E-Mail-Adresse und ein temporäres Kennwort ein.
+
Der Benutzer muss das Passwort bei der ersten Anmeldung ändern.

. Wählen Sie eine Benutzerrolle mit den entsprechenden Systemberechtigungen aus.
+
Jede Rolle bietet die folgenden Berechtigungen:

+
** Ein *Viewer* kann Ressourcen anzeigen.
** Ein *Mitglied* verfügt über Berechtigungen für Viewer-Rollen und kann Apps und Cluster verwalten, Apps verwalten und Snapshots und Backups löschen.
** Ein *Admin* verfügt über Berechtigungen für die Mitgliederrolle und kann alle anderen Benutzer außer dem Eigentümer hinzufügen und entfernen.
** Ein *Owner* hat Administratorrechte und kann beliebige Benutzerkonten hinzufügen und entfernen.


. Um einem Benutzer mit einer Mitglied- oder Viewer-Rolle Einschränkungen hinzuzufügen, aktivieren Sie das Kontrollkästchen * Rolle auf Einschränkungen beschränken*.
+
Weitere Informationen zum Hinzufügen von Einschränkungen finden Sie unter link:manage-roles.html["Rollen managen"].

. Wählen Sie *Hinzufügen*.




== Passwörter verwalten

Sie können Passwörter für Benutzerkonten im Astra Control Center verwalten.



=== Passwort ändern

Sie können das Passwort Ihres Benutzerkontos jederzeit ändern.

.Schritte
. Klicken Sie oben rechts auf dem Bildschirm auf das Symbol Benutzer.
. Wählen Sie *Profil*.
. Wählen Sie im Menü Optionen in der Spalte *Aktionen* die Option *Passwort ändern* aus.
. Geben Sie ein Passwort ein, das den Anforderungen des Passworts entspricht.
. Geben Sie das Kennwort zur Bestätigung erneut ein.
. Wählen Sie *Passwort ändern*.




=== Kennwort eines anderen Benutzers zurücksetzen

Wenn Ihr Konto über Berechtigungen für die Administrator- oder Eigentümerrolle verfügt, können Sie Passwörter für andere Benutzerkonten sowie für Ihre eigenen zurücksetzen. Wenn Sie ein Kennwort zurücksetzen, weisen Sie ein temporäres Kennwort zu, das der Benutzer bei der Anmeldung ändern muss.

.Schritte
. Wählen Sie im Navigationsbereich * Konto verwalten* die Option *Konto*.
. Wählen Sie die Dropdown-Liste *Aktionen* aus.
. Wählen Sie *Passwort Zurücksetzen*.
. Geben Sie ein temporäres Kennwort ein, das den Anforderungen des Passworts entspricht.
. Geben Sie das Kennwort zur Bestätigung erneut ein.
+

NOTE: Wenn sich der Benutzer beim nächsten Mal anmeldet, wird er aufgefordert, das Passwort zu ändern.

. Wählen Sie *Passwort zurücksetzen*.




== Ändern Sie die Rolle eines Benutzers

Benutzer mit der Rolle „Eigentümer“ können die Rolle aller Benutzer ändern, während Benutzer mit der Administratorrolle die Rolle von Benutzern ändern können, die die Rolle „Administrator“, „Mitglied“ oder „Viewer“ haben.

.Schritte
. Wählen Sie im Navigationsbereich * Konto verwalten* die Option *Konto*.
. Wählen Sie die Dropdown-Liste *Aktionen* aus.
. Wählen Sie *Rolle bearbeiten*.
. Wählen Sie eine neue Rolle aus.
. Um Einschränkungen auf die Rolle anzuwenden, aktivieren Sie das Kontrollkästchen *Rolle auf Einschränkungen beschränken* und wählen Sie eine Bedingung aus der Liste aus.
+
Wenn es keine Einschränkungen gibt, können Sie eine Bedingung hinzufügen. Weitere Informationen finden Sie unter link:manage-roles.html["Rollen managen"].

. Wählen Sie *Bestätigen*.


Astra Control Center aktualisiert die Benutzerberechtigungen auf der Grundlage der neuen Rolle, die Sie ausgewählt haben.



== Benutzer entfernen

Benutzer mit der Eigentümer- oder Administratorrolle können jederzeit andere Benutzer aus dem Konto entfernen.

.Schritte
. Wählen Sie im Navigationsbereich * Konto verwalten* die Option *Konto*.
. Aktivieren Sie auf der Registerkarte *Benutzer* das Kontrollkästchen in der Zeile jedes Benutzers, den Sie entfernen möchten.
. Wählen Sie im Menü Optionen in der Spalte *Aktionen* die Option *Benutzer/s entfernen* aus.
. Wenn Sie aufgefordert werden, bestätigen Sie den Löschvorgang, indem Sie das Wort "Entfernen" eingeben und dann *Ja, Benutzer entfernen* wählen.


Astra Control Center entfernt den Benutzer aus dem Konto.
