---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Hier wird beschrieben, wie Sie das Astra Control Center und den Astra Control Center Operator entfernen. 
---
= Deinstallieren Sie Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Möglicherweise müssen Sie die Komponenten des Astra Control Center entfernen, wenn Sie ein Upgrade von einer Testversion auf eine Vollversion des Produkts durchführen. Um Astra Control Center und den Astra Control Center Operator zu entfernen, führen Sie die in diesem Verfahren beschriebenen Befehle nacheinander aus.

Wenn Sie Probleme mit der Deinstallation haben, lesen Sie <<Fehlerbehebung bei Deinstallationsproblemen>>.

.Bevor Sie beginnen
. link:../use/unmanage.html#unmanage-an-app["Heben Sie die Verwaltung aller Apps auf"^] Auf den Clustern.
. link:../use/unmanage.html#unmanage-a-cluster["Heben Sie die Verwaltung aller Cluster auf"^].


.Schritte
. Löschen Sie Das Astra Control Center. Der folgende Beispielbefehl basiert auf einer Standardinstallation. Ändern Sie den Befehl, wenn Sie benutzerdefinierte Konfigurationen erstellt haben.
+
[listing]
----
kubectl delete -f astra_control_center.yaml -n netapp-acc
----
+
Ergebnis:

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Löschen Sie den mit dem folgenden Befehl `netapp-acc` (Oder benutzerdefinierter Name) Namespace:
+
[listing]
----
kubectl delete ns [netapp-acc or custom namespace]
----
+
Beispielergebnis:

+
[listing]
----
namespace "netapp-acc" deleted
----
. Löschen Sie die Komponenten des Astra Control Center-Bedienersystems mit dem folgenden Befehl:
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Ergebnis:

+
[listing]
----
namespace/netapp-acc-operator deleted
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io deleted
role.rbac.authorization.k8s.io/acc-operator-leader-election-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role deleted
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding deleted
configmap/acc-operator-manager-config deleted
service/acc-operator-controller-manager-metrics-service deleted
deployment.apps/acc-operator-controller-manager deleted
----




== Fehlerbehebung bei Deinstallationsproblemen

Verwenden Sie die folgenden Problemumgehungen, um Probleme bei der Deinstallation von Astra Control Center zu beheben.



=== Bei der Deinstallation des Astra Control Center wird der Monitor-Operator POD im Managed Cluster nicht bereinigt

Wenn Sie das Management Ihrer Cluster nicht rückgängig gemacht haben, bevor Sie Astra Control Center deinstalliert haben, können Sie die Pods im netapp-Monitoring Namespace und den Namespace manuell mit den folgenden Befehlen löschen:

.Schritte
. Löschen `acc-monitoring` Agent:
+
[listing]
----
kubectl delete agents acc-monitoring -n netapp-monitoring
----
+
Ergebnis:

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. Löschen Sie den Namespace:
+
[listing]
----
kubectl delete ns netapp-monitoring
----
+
Ergebnis:

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. Bestätigen der entfernten Ressourcen:
+
[listing]
----
kubectl get pods -n netapp-monitoring
----
+
Ergebnis:

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. Bestätigen Sie, dass der Monitoring Agent entfernt wurde:
+
[listing]
----
kubectl get crd|grep agent
----
+
Beispielergebnis:

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. Informationen zur benutzerdefinierten Ressourcendefinition löschen:
+
[listing]
----
kubectl delete crds agents.monitoring.netapp.com
----
+
Ergebnis:

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




=== Bei der Deinstallation von Astra Control Center werden die Traefik CRDs nicht bereinigt

Sie können die Traefik-CRDs manuell löschen. CRDs sind globale Ressourcen, und das Löschen kann sich auf andere Anwendungen auf dem Cluster auswirken.

.Schritte
. Führen Sie die auf dem Cluster installierten Traefik-CRDs auf:
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
Antwort

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
middlewaretcps.traefik.containo.us            2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. Löschen Sie die CRDs:
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us middlewaretcps.traefik.containo.us
----




== Weitere Informationen

* link:../release-notes/known-issues.html["Bekannte Probleme bei der Deinstallation"]

