---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters, tanzu, tkg, tkgi, grid, kubernetes, k8s 
summary: 'Erste Schritte mit Astra Control Center: Überprüfen Sie die Unterstützung Ihrer Kubernetes Cluster, Applikationen und Webbrowser.' 
---
= Anforderungen des Astra Control Centers
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Prüfen Sie zunächst die Bereitschaft Ihrer Betriebsumgebung, Anwendungscluster, Applikationen, Lizenzen und Ihres Webbrowsers. Stellen Sie sicher, dass Ihre Umgebung für den Einsatz und Betrieb von Astra Control Center diese Anforderungen erfüllt.



== Unterstützte Host-Cluster-Kubernetes-Umgebungen

Astra Control Center wurde mit den folgenden Kubernetes-Host-Umgebungen validiert:


NOTE: Stellen Sie sicher, dass die Kubernetes-Umgebung, für die Sie Astra Control Center hosten, die grundlegenden Ressourcenanforderungen erfüllt, die in der offiziellen Dokumentation der Umgebung aufgeführt sind.

|===
| Kubernetes-Distribution auf Host-Cluster | Unterstützte Versionen 


| Azure Kubernetes Service für Azure Stack HCI | Azure Stack HCI 21H2 und 22H2 mit AKS 1.24.x und 1.25.x 


| Google Anthos | 1.15 bis 1.16 (siehe <<Anforderungen für Google Anthos Ingress>>) 


| Kubernetes (Vorgelagert) | 1.26 bis 1.28 


| Rancher Kubernetes Engine (RKE) | RKE 1.3 mit Rancher Manager 2.6
RKE 1.4 mit Rancher Manager 2.7
RKE 2 (v1.24.x) mit Rancher 2.6
RKE 2 (v1.26.x) mit Rancher 2.7 


| Red hat OpenShift Container Platform | 4.11 bis 4.13 


| VMware Tanzu Kubernetes Grid Integrated Edition | 1.16.x (siehe <<Ressourcenanforderungen des Host-Clusters>>) 
|===


== Ressourcenanforderungen des Host-Clusters

Astra Control Center erfordert zusätzlich zu den Ressourcenanforderungen der Umgebung die folgenden Ressourcen:


NOTE: Bei diesen Anforderungen wird davon ausgegangen, dass Astra Control Center die einzige Applikation ist, die in der Betriebsumgebung ausgeführt wird. Wenn in der Umgebung zusätzliche Applikationen ausgeführt werden, passen Sie diese Mindestanforderungen entsprechend an.

* *CPU-Erweiterungen*: Die CPUs in allen Knoten der Hosting-Umgebung müssen AVX-Erweiterungen aktiviert haben.
* *Worker Nodes*: Insgesamt mindestens 3 Worker Nodes, mit 4 CPU Cores und je 12 GB RAM
* *Anforderungen für den VMware Tanzu Kubernetes Grid Cluster*: Beachten Sie bei der Hosting von Astra Control Center auf einem VMware Tanzu Kubernetes Grid (TKG)- oder Tanzu Kubernetes Grid Integrated Edition (TKGi)-Cluster die folgenden Überlegungen.
+
** Das standardmäßige VMware TKG- und TKGi-Konfigurationstoken läuft zehn Stunden nach der Bereitstellung ab. Wenn Sie Tanzu Portfolio-Produkte verwenden, müssen Sie eine Tanzu Kubernetes Cluster-Konfigurationsdatei mit einem nicht auslaufenden Token generieren, um Verbindungsprobleme zwischen Astra Control Center und verwalteten Anwendungsclustern zu vermeiden. Anweisungen finden Sie unter https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/nsx-application-platform/GUID-52A52C0B-9575-43B6-ADE2-E8640E22C29F.html["Die Produktdokumentation zu VMware NSX-T Data Center."^]
** Verwenden Sie die `kubectl get nsxlbmonitors -A` Befehl, um zu sehen, ob bereits ein Service-Monitor für die Annahme von Ingress-Traffic konfiguriert ist. Wenn vorhanden, sollten Sie MetalLB nicht installieren, da der vorhandene Servicemonitor eine neue Load Balancer-Konfiguration außer Kraft setzt.
** Deaktivieren Sie die Durchsetzung der Standardspeicherklasse TKG oder TKGi auf allen Anwendungsclustern, die von Astra Control verwaltet werden sollen. Sie können dies tun, indem Sie die bearbeiten `TanzuKubernetesCluster` Ressource auf dem Namespace-Cluster.
** Achten Sie bei der Implementierung des Astra Control Center in einer TKG- oder TKGi-Umgebung auf die speziellen Anforderungen von Astra Trident. Weitere Informationen finden Sie im https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#other-known-configuration-options["Astra Trident-Dokumentation"^].






== Service-Mesh-Anforderungen

Eine unterstützte Vanilla-Version des Istio Service Mesh wird dringend empfohlen, auf dem Astra Control Center Host Cluster installiert zu werden. Siehe https://istio.io/latest/docs/releases/supported-releases/["Unterstützte Versionen"^] Für unterstützte Versionen von Istio. Markenversionen von Istio Service-Mesh, wie OpenShift Service Mesh, werden nicht mit Astra Control Center validiert.

Um Astra Control Center mit dem auf dem Host-Cluster installierten Istio-Service-Mesh zu integrieren, müssen Sie die Integration im Astra Control Center vornehmen link:../get-started/install_acc.html["Installation"] Prozess und nicht unabhängig von diesem Prozess.


NOTE: Wenn Sie Astra Control Service installieren, ohne ein Service-Mesh auf dem Host-Cluster zu konfigurieren, hat dies möglicherweise schwerwiegende Auswirkungen auf die Sicherheit.



== Anforderungen von Astra Trident

Stellen Sie sicher, dass Sie die folgenden Anforderungen für Astra Trident erfüllen, die Ihren Anforderungen Ihrer Umgebung entsprechen:

* *Mindestversion für Astra Control Center*: Astra Trident 23.01 oder neuer installiert und konfiguriert
* *ONTAP-Konfiguration mit Astra Trident*:
+
** *Storage class*: Konfigurieren Sie mindestens eine Astra Trident Storage-Klasse auf dem Cluster. Wenn eine Standard-Storage-Klasse konfiguriert ist, stellen Sie sicher, dass es die einzige Storage-Klasse mit der Standardbezeichnung ist.
** *Speichertreiber und Workerknoten*: Stellen Sie sicher, dass Sie die Workerknoten in Ihrem Cluster mit den entsprechenden Speichertreibern konfigurieren, damit die Pods mit dem Backend-Speicher interagieren können. Astra Control Center unterstützt die folgenden ONTAP-Treiber von Astra Trident:
+
*** `ontap-nas`
*** `ontap-san`
*** `ontap-san-economy` (App-Replizierung ist bei diesem Storage-Klassen-Typ nicht verfügbar)
*** `ontap-nas-economy` (Snapshots, Replizierungsrichtlinien und Sicherungsrichtlinien stehen bei diesem Typ von Storage-Klassen nicht zur Verfügung.)








== Astra Control Provisioner

Um die erweiterten Storage-Funktionen von Astra Control Provisioner zu verwenden, müssen Sie Astra Trident 23.10 oder höher installieren und aktivieren link:../use/enable-acp.html["Funktionen für die Astra Control Provisioner"].



== Storage-Back-Ends

Stellen Sie sicher, dass Sie ein unterstütztes Backend mit ausreichender Kapazität haben.

* *Erforderliche Back-End-Speicherkapazität*: Mindestens 500 GB verfügbar
* *Unterstützte Backends*: Astra Control Center unterstützt folgende Speicher-Backends:
+
** NetApp ONTAP 9.9.1 oder neuer AFF, FAS und ASA Systeme
** NetApp ONTAP Select 9.9.1 oder höher
** NetApp Cloud Volumes ONTAP 9.9.1 oder höher
** Longhorn 1.5.0 oder neuer
+
*** Erfordert die manuelle Erstellung eines VolumeSnapshotClass-Objekts. Siehe https://longhorn.io/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/#create-a-csi-volumesnapshot-associated-with-longhorn-snapshot["Longhorn-Dokumentation"^] Weitere Anweisungen.


** NetApp MetroCluster
+
*** Verwaltete Kubernetes-Cluster müssen in einer Stretch-Konfiguration vorliegen.


** Storage-Back-Ends bei unterstützten Cloud-Providern verfügbar






=== ONTAP-Lizenzen

Um Astra Control Center zu nutzen, müssen Sie je nach den Anforderungen die folgenden ONTAP-Lizenzen besitzen:

* FlexClone
* SnapMirror: Optional Nur für die Replizierung auf Remote-Systeme mit SnapMirror Technologie erforderlich. Siehe https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Informationen zu SnapMirror Lizenzen"^].
* S3-Lizenz: Optional Nur für ONTAP S3 Buckets erforderlich


Informationen darüber, ob auf Ihrem ONTAP System die erforderlichen Lizenzen vorhanden sind, finden Sie unter https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Managen Sie ONTAP Lizenzen"^].



=== NetApp MetroCluster

Wenn Sie NetApp MetroCluster als Storage-Backend verwenden, müssen Sie Folgendes tun:

* Geben Sie eine SVM-Management-LIF als Back-End-Option im von Ihnen verwendeten Astra Trident-Treiber an
* Stellen Sie sicher, dass Sie über die entsprechende ONTAP-Lizenz verfügen


Weitere MetroCluster Informationen zu den einzelnen Treibern finden Sie in der Dokumentation zu Astra Trident:

* https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["San"^]
* https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html["NAS"^]




== Bildregistrierung

Sie müssen über eine vorhandene private Docker Image-Registrierung verfügen, auf die Sie Astra Control Center Build-Images übertragen können. Sie müssen die URL der Bildregistrierung angeben, in der Sie die Bilder hochladen.



== Astra Control Center-Lizenz

Für Astra Control Center ist eine Astra Control Center Lizenz erforderlich. Bei der Installation von Astra Control Center ist bereits eine eingebettete 90-Tage-Evaluierungslizenz für 4,800 CPU-Einheiten aktiviert. Wenn Sie mehr Kapazität oder andere Evaluierungsbedingungen benötigen, oder ein Upgrade auf eine komplette Lizenz wünschen, können Sie eine andere Evaluierungslizenz oder volle Lizenz von NetApp erhalten. Sie benötigen eine Lizenz zum Schutz Ihrer Applikationen und Daten.

Astra Control Center können Sie ausprobieren, indem Sie sich für eine kostenlose Testversion anmelden. Registrieren Sie sich link:https://bluexp.netapp.com/astra-register["Hier"^].

Informationen zum Einrichten der Lizenz finden Sie unter link:setup_overview.html["Verwenden Sie eine 90-Tage-Evaluierungslizenz"^].

Weitere Informationen zur Funktionsweise von Lizenzen finden Sie unter link:../concepts/licensing.html["Lizenzierung"^].



== Netzwerkanforderungen

Konfigurieren Sie Ihre Betriebsumgebung so, dass Astra Control Center ordnungsgemäß kommunizieren kann. Die folgenden Netzwerkkonfigurationen sind erforderlich:

* *FQDN-Adresse*: Sie müssen eine FQDN-Adresse für Astra Control Center haben.
* *Zugang zum Internet*: Sie sollten festlegen, ob Sie Zugang zum Internet von außen haben. Wenn nicht, sind einige Funktionen möglicherweise begrenzt, beispielsweise das Empfangen von Monitoring- und Kennzahlendaten von NetApp Cloud Insights oder das Senden von Support-Paketen an die https://mysupport.netapp.com/site/["NetApp Support Website"^].
* *Port Access*: Die Betriebsumgebung, die das Astra Control Center hostet, kommuniziert über die folgenden TCP-Ports. Sie sollten sicherstellen, dass diese Ports über beliebige Firewalls zugelassen sind, und Firewalls so konfigurieren, dass jeder HTTPS-ausgehenden Datenverkehr aus dem Astra-Netzwerk zugelassen wird. Einige Ports erfordern Verbindungen zwischen der Umgebung, in der Astra Control Center gehostet wird, und jedem verwalteten Cluster (sofern zutreffend).



NOTE: Sie können Astra Control Center in einem Dual-Stack-Kubernetes-Cluster implementieren. Astra Control Center kann Applikationen und Storage-Back-Ends managen, die für den Dual-Stack-Betrieb konfiguriert wurden. Weitere Informationen zu Dual-Stack-Cluster-Anforderungen finden Sie im https://kubernetes.io/docs/concepts/services-networking/dual-stack/["Kubernetes-Dokumentation"^].

|===
| Quelle | Ziel | Port | Protokoll | Zweck 


| Client-PC | Astra Control Center | 443 | HTTPS | UI-/API-Zugriff – Stellen Sie sicher, dass dieser Port in beide Richtungen zwischen Astra Control Center und dem System offen ist, mit dem auf Astra Control Center zugegriffen wird 


| Kennzahlenverbraucher | Astra Control Center Worker-Node | 9090 | HTTPS | Kennzahlen Datenkommunikation - sicherstellen, dass jeder verwaltete Cluster auf diesen Port auf dem Cluster zugreifen kann, das Astra Control Center hostet (Kommunikation in zwei Bereichen erforderlich) 


| Astra Control Center | Gehosteter Cloud Insights Service  | 443 | HTTPS | Cloud Insights Kommunikation 


| Astra Control Center | Amazon S3 Storage-Bucket-Provider | 443 | HTTPS | Amazon S3 Storage-Kommunikation 


| Astra Control Center | NetApp AutoSupport  | 443 | HTTPS | Kommunikation zwischen NetApp AutoSupport 


| Astra Control Center | Gemanagter Kubernetes-Cluster | 443/6443
*HINWEIS*: Der Port, den der verwaltete Cluster verwendet, kann je nach Cluster variieren. Informationen finden Sie in der Dokumentation des Anbieters der Cluster-Software. | HTTPS | Kommunikation mit dem verwalteten Cluster – Stellen Sie sicher, dass dieser Port auf beiden Wegen zwischen dem Cluster, der Astra Control Center hostet, und jedem verwalteten Cluster offen ist 
|===


== Ingress für lokale Kubernetes Cluster

Sie können die Art der Netzwerk Ingress Astra Control Center verwendet wählen. Astra Control Center nutzt standardmäßig das Astra Control Center Gateway (Service/Trafik) als Cluster-weite Ressource. Astra Control Center unterstützt auch den Einsatz eines Service Load Balancer, sofern diese in Ihrer Umgebung zugelassen sind. Wenn Sie lieber einen Service-Load-Balancer verwenden und noch nicht eine konfiguriert haben, können Sie den MetalLB-Load-Balancer verwenden, um dem Dienst automatisch eine externe IP-Adresse zuzuweisen. In der Konfiguration des internen DNS-Servers sollten Sie den ausgewählten DNS-Namen für Astra Control Center auf die Load-Balanced IP-Adresse verweisen.


NOTE: Der Load Balancer sollte eine IP-Adresse verwenden, die sich im gleichen Subnetz wie die IP-Adressen des Astra Control Center Worker-Knotens befindet.

Weitere Informationen finden Sie unter link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["Eindringen für den Lastenausgleich einrichten"^].



=== Anforderungen für Google Anthos Ingress

Beachten Sie beim Hosten von Astra Control Center auf einem Google Anthos Cluster, dass Google Anthos standardmäßig den MetalLB Load Balancer und den Istio Ingress Service enthält, sodass Sie während der Installation einfach die generischen Ingress-Funktionen von Astra Control Center verwenden können. Siehe link:install_acc.html#configure-astra-control-center["Konfigurieren Sie Astra Control Center"^] Entsprechende Details.



== Unterstützte Webbrowser

Astra Control Center unterstützt aktuelle Versionen von Firefox, Safari und Chrome mit einer Mindestauflösung von 1280 x 720.



== Zusätzliche Anforderungen an Applikations-Cluster

Beachten Sie diese Anforderungen, wenn Sie die folgenden Funktionen des Astra Control Center nutzen möchten:

* *Anforderungen an den Anwendungscluster*: link:../get-started/setup_overview.html#prepare-your-environment-for-cluster-management-using-astra-control["Anforderungen für das Cluster-Management"^]
+
** *Verwaltete Anwendungsanforderungen*: link:../use/manage-apps.html#application-management-requirements["Anforderungen für das Applikationsmanagement"^]
** *Zusätzliche Anforderungen für die Anwendungsreplikation*: link:../use/replicate_snapmirror.html#replication-prerequisites["Replikationsvoraussetzungen"^]






== Wie es weiter geht

Sehen Sie sich die an link:quick-start.html["Schnellstart"^] Überblick.
