---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden. 
---
= Bekannte Probleme
:hardbreaks:
:allow-uri-read: 
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden.

Die folgenden bekannten Probleme wirken sich auf die aktuelle Version aus:

.Anwendungen
* <<Die Wiederherstellung einer App führt zu einer PV-Größe, die größer ist als das ursprüngliche PV>>
* <<Applikationsklone können nicht mit einer bestimmten Version von PostgreSQL verwendet werden>>
* <<Anwendungsklone sind bei der Verwendung von OCP-Sicherheitskontextsensitonen (SCC) auf Servicekontoebene fehlgeschlagen.>>
* <<Applikationsklone scheitern, nachdem eine Applikation mit einer festgelegten Storage-Klasse implementiert wurde>>
* <<App-Backups und Snapshots schlagen fehl, wenn die Volume-Snapshot-Klasse nach dem Management eines Clusters hinzugefügt wird>>


.Cluster
* <<Das Verwalten eines Clusters mit Astra Control Center schlägt fehl, wenn die standardmäßige kubeconfig-Datei mehr als einen Kontext enthält>>
* <<Einige Pods können nach dem Upgrade auf Astra Control Center 23.04 nicht gestartet werden>>
* <<Ein Monitoring-Pod kann in Istio Umgebungen zum Absturz kommen>>


.Andere Probleme
* <<Verwaltete Cluster werden nicht in NetApp Cloud Insights angezeigt, wenn die Verbindung über einen Proxy hergestellt wird>>
* <<Das Management der App-Daten schlägt mit Fehler des internen Service (500) fehl, wenn Astra Trident offline ist>>




== Die Wiederherstellung einer App führt zu einer PV-Größe, die größer ist als das ursprüngliche PV

Wenn Sie ein persistentes Volume nach der Erstellung eines Backups skalieren und dann aus diesem Backup wiederherstellen, wird die Größe des persistenten Volumes an die neue PV-Größe angepasst, anstatt die Backup-Größe zu verwenden.



== Applikationsklone können nicht mit einer bestimmten Version von PostgreSQL verwendet werden

App-Klone innerhalb desselben Clusters schlagen konsequent mit dem Bitnami PostgreSQL 11.5.0 Diagramm fehl. Um erfolgreich zu klonen, verwenden Sie eine frühere oder höhere Version des Diagramms.



== Anwendungsklone sind bei der Verwendung von OCP-Sicherheitskontextsensitonen (SCC) auf Servicekontoebene fehlgeschlagen.

Ein Applikationsklon kann fehlschlagen, wenn die ursprünglichen Einschränkungen des Sicherheitskontexts auf der Service-Kontoebene im Namespace im Cluster der OpenShift Container Platform konfiguriert sind. Wenn der Anwendungsklon ausfällt, wird er im Bereich Managed Applications im Astra Control Center mit dem Status angezeigt `Removed`. Siehe https://["knowledgebase-Artikel"^] Finden Sie weitere Informationen.



== App-Backups und Snapshots schlagen fehl, wenn die Volume-Snapshot-Klasse nach dem Management eines Clusters hinzugefügt wird

Backups und Snapshots schlagen fehl `UI 500 error` In diesem Szenario. Aktualisieren Sie die App-Liste als Workaround.



== Applikationsklone scheitern, nachdem eine Applikation mit einer festgelegten Storage-Klasse implementiert wurde

Nachdem eine Applikation mit einer Storage-Klasse bereitgestellt wurde (z. B. `helm install ...-set global.storageClass=netapp-cvs-perf-extreme`). Nachfolgende Klonversuche der Applikation erfordern, dass das Ziel-Cluster die ursprünglich angegebene Storage-Klasse hat. Das Klonen einer Applikation mit einer explizit festgelegten Storage-Klasse auf ein Cluster ohne dieselbe Storage-Klasse schlägt fehl. Es gibt keine Wiederherstellungsschritte in diesem Szenario.



== Das Verwalten eines Clusters mit Astra Control Center schlägt fehl, wenn die standardmäßige kubeconfig-Datei mehr als einen Kontext enthält

Sie können ein kubeconfig nicht mit mehr als einem Cluster und Kontext darin verwenden. Siehe link:https://kb.netapp.com/Cloud/Astra/Control/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["knowledgebase-Artikel"^] Finden Sie weitere Informationen.



== Einige Pods können nach dem Upgrade auf Astra Control Center 23.04 nicht gestartet werden

Nach dem Upgrade auf Astra Control Center 23.04 können einige Pods möglicherweise nicht gestartet werden. Um dies zu umgehen, starten Sie die betroffenen Pods mithilfe der folgenden Schritte manuell neu:

. Ermitteln Sie die betroffenen Pods, und ersetzen Sie <namespace> durch den aktuellen Namespace:
+
[listing]
----
kubectl get pods -n <namespace> | grep au-pod
----
+
Die betroffenen Pods haben ähnliche Ergebnisse wie die folgenden:

+
[listing]
----
pcloud-astra-control-center-au-pod-0 0/1 CreateContainerConfigError 0 13s
----
. Starten Sie jeden betroffenen Pod neu, indem Sie <namespace> durch den aktuellen Namespace ersetzen:
+
[listing]
----
kubectl delete pod pcloud-astra-control-center-au-pod-0 -n <namespace>
----




== Ein Monitoring-Pod kann in Istio Umgebungen zum Absturz kommen

Wenn Sie Astra Control Center mit Cloud Insights in einer Istio Umgebung koppeln, bietet die `telegraf-rs` Pod kann abstürzen. Führen Sie als Workaround die folgenden Schritte aus:

. Suchen Sie den abgestürzten POD:
+
[listing]
----
kubectl -n netapp-monitoring get pod | grep Error
----
+
Sie sollten eine Ausgabe wie die folgende sehen:

+
[listing]
----
NAME READY STATUS RESTARTS AGE
telegraf-rs-fhhrh 1/2 Error 2 (26s ago) 32s
----
. Starten Sie den abgestürzten Pod neu, und ersetzen Sie ihn `<pod_name_from_output>` Mit dem Namen des betroffenen Pods:
+
[listing]
----
kubectl -n netapp-monitoring delete pod <pod_name_from_output>
----
+
Sie sollten eine Ausgabe wie die folgende sehen:

+
[listing]
----
pod "telegraf-rs-fhhrh" deleted
----
. Überprüfen Sie, ob der Pod neu gestartet wurde und sich nicht im Fehlerzustand befindet:
+
[listing]
----
kubectl -n netapp-monitoring get pod
----
+
Sie sollten eine Ausgabe wie die folgende sehen:

+
[listing]
----
NAME READY STATUS RESTARTS AGE
telegraf-rs-rrnsb 2/2 Running 0 11s
----




== Verwaltete Cluster werden nicht in NetApp Cloud Insights angezeigt, wenn die Verbindung über einen Proxy hergestellt wird

Wenn Astra Control Center eine Verbindung zu NetApp Cloud Insights über einen Proxy herstellt, werden gemanagte Cluster möglicherweise nicht im Cloud Insights angezeigt. Führen Sie als Workaround die folgenden Befehle auf jedem verwalteten Cluster aus:

[source, console]
----
kubectl get cm telegraf-conf -o yaml -n netapp-monitoring | sed '/\[\[outputs.http\]\]/c\    [[outputs.http]]\n    use_system_proxy = true' | kubectl replace -f -
----
[source, console]
----
kubectl get cm telegraf-conf-rs -o yaml -n netapp-monitoring | sed '/\[\[outputs.http\]\]/c\    [[outputs.http]]\n    use_system_proxy = true' | kubectl replace -f -
----
[source, console]
----
kubectl get pods -n netapp-monitoring --no-headers=true | grep 'telegraf-ds\|telegraf-rs' | awk '{print $1}' | xargs kubectl delete -n netapp-monitoring pod
----


== Das Management der App-Daten schlägt mit Fehler des internen Service (500) fehl, wenn Astra Trident offline ist

Wenn Astra Trident auf einem App-Cluster offline geschaltet wird (und wieder online geschaltet wird) und 500 interne Servicefehler auftreten, wenn versucht wird, das App-Datenmanagement zu managen, starten Sie alle Kubernetes-Nodes im App-Cluster neu, um die Funktionalität wiederherzustellen.



== Weitere Informationen

* link:../release-notes/known-limitations.html["Bekannte Einschränkungen"]

