---
sidebar: sidebar 
permalink: release-notes/known-issues-ads.html 
keywords: astra, control center, ads, data store, bugs, known issues, problems 
summary: Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden. 
---
= Bekannte Probleme bei Astra Data Store und dieser Version des Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden.

https://docs.netapp.com/us-en/astra-data-store/release-notes/known-issues.html["Sehen Sie sich diese zusätzlichen bekannten Probleme bei Astra Data Store an"^] Das könnte sich mit der aktuellen Version des Astra Control Center auch auf das Management des Astra Data Stores auswirken.



== Die Volume-Details des Astra Data Store werden auf der Seite Storage Backends der Astra Control Center-Benutzeroberfläche nicht angezeigt

Details wie Kapazität und Durchsatz werden nicht in der UI angezeigt. Wenn dieses Problem auftritt, heben Sie die Verwaltung des Storage-Back-End von und fügen Sie es erneut hinzu.



== Um einen Cluster mit Astra Data Store zu verwalten, muss zunächst eine gemanagte System-App entfernt werden

Wenn Sie einem Astra Control Center-Cluster einen Cluster mit Astra Data Store hinzugefügt haben, wird die astrads-System-App standardmäßig als versteckte Anwendung verwaltet. Um das Cluster zu verwalten, müssen Sie zuerst die Astrads-System-App rückgängig machen. Die Verwaltung dieser App kann mit der Astra Control Center-Benutzeroberfläche nicht aufgehoben werden. Verwenden Sie stattdessen eine Astra Control API-Anfrage, um die App manuell zu entfernen:

.Details
====
.Schritte
. Holen Sie sich die ID für den verwalteten Cluster mithilfe dieser API:
+
[listing]
----
/accounts/{account_id}/topology/v1/managedClusters
----
+
Antwort:

+
[listing, subs="+quotes"]
----
{
"items": [
{
"type": "application/astra-managedCluster",
"version": "1.1",
*"id": "123ab987-0bc0-00d0-a00a-1234567abd8d",*
"name": "astrads-cluster-1234567",
...
----
. Abrufen der App „Managed astrads-System“:
+
[listing]
----
/accounts/{account_id}/topology/v2/managedClusters/{managedCluster_id}/apps
----
+
Antwort:

+
[listing, subs="+quotes"]
----
{
  "items": [
    [
      *"1b011d11-bb88-40c7-a1a1-ab1234c123d3",*
      "astrads-system",
      "ready"
    ]
  ],
  "metadata": {}
}
----
. Löschen Sie die App astrads-System mit der App-ID, die Sie im vorherigen Schritt erworben haben (`1b011d11-bb88-40c7-a1a1-ab1234c123d3`).
+
[listing]
----
/accounts/{account_id}/k8s/v2/apps/{astrads-system_app_id}
----


====


== Weitere Informationen

* link:../release-notes/known-issues.html["Bekannte Probleme"]
* link:../release-notes/known-limitations.html["Bekannte Einschränkungen"]

